# Generated by Django 3.2.24 on 2024-02-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
                ('tipo_cliente', models.CharField(choices=[('Hogar', 'Hogar'), ('Empresa', 'Empresa')], max_length=20)),
                ('tipo_registro', models.CharField(choices=[('Taller', 'Taller'), ('En Línea', 'En Línea')], max_length=20)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Usuario', 'Usuario')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Portatil', 'Portatil'), ('Escritorio', 'Escritorio'), ('Impresora', 'Impresora'), ('Componente', 'Componente')], max_length=20)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('serie', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaNoIniciado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField()),
                ('descripcion_corta', models.CharField(max_length=100)),
                ('estado_fisico', models.CharField(blank=True, max_length=250)),
                ('componente_adjunto', models.CharField(blank=True, max_length=250)),
                ('incidencia_no_iniciado', models.TextField()),
                ('observacion_no_iniciado', models.TextField(blank=True)),
                ('costo_revision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_servicio', models.CharField(choices=[('Remoto', 'Remoto'), ('Taller', 'Taller'), ('Insitu', 'Insitu')], max_length=20)),
                ('estado', models.CharField(choices=[('No Iniciado', 'No Iniciado'), ('En Proceso', 'En Proceso'), ('Confirmación', 'Confirmación'), ('Confirmación', 'Confirmación'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.cliente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('Cliente', 'Cliente'), ('Usuario', 'Usuario')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_proceso', models.TextField()),
                ('observacion_proceso', models.TextField(blank=True)),
                ('costo_adicional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.cliente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.dispositivo')),
                ('incidencia_no_iniciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.incidencianoiniciado')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_finalizado', models.TextField(blank=True)),
                ('observaciones_finalizado', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.cliente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.dispositivo')),
                ('incidencia_no_iniciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.incidencianoiniciado')),
                ('incidencia_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.incidenciaproceso')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaConfirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacion', models.CharField(choices=[('En espera', 'En espera'), ('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.cliente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.dispositivo')),
                ('incidencia_no_iniciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.incidencianoiniciado')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaAnulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_anulado', models.TextField()),
                ('observaciones_anulado', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.cliente')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.dispositivo')),
                ('incidencia_no_iniciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.incidencianoiniciado')),
            ],
        ),
    ]
